### ISSUE TITLE
No option to choose network interface

### ISSUE THREAD

**Issue by orangy57** [Urferu/Lan-Play-Server-Manager#3]
Either I can't find it or figure it out, but the program automatically defaults to the wrong network interface, with no option to change it beforehand.

**Comment by clockterra** [comment]
untick select interface, and then when you try to conect it will ask you for the interaface in the console window.

**Comment by Urferu** [comment]
The program has a checked check called "Select network interface" if you deactivate it it will allow you to select the interface from lan-play console
