### ISSUE TITLE
Google warning about virus and alert on virustotal.com

### ISSUE THREAD

**Issue by KyoFaBraL** [Urferu/Lan-Play-Server-Manager#4]
i uploaded the file for my drive and shared with friends, but the google antivirus wont let others to download the file.
![virus](https://user-images.githubusercontent.com/37299702/50606741-8a0cd400-0ea5-11e9-9f1e-97410ee3c30b.png)
![captura de tela 2019-01-02 as 15 41 45](https://user-images.githubusercontent.com/37299702/50606755-985af000-0ea5-11e9-861b-98e18103adb2.png)

**Comment by Urferu** [comment]
antivirus for unregistered applications are always marked as viruses, but in some antivirus you must pay to register them and for obvious reasons I have not registered this application.

**Comment by clockterra** [comment]
caiofcabral, tell your friends that try to download the one from here, and let us know if they can install it...
downloading from github will give virus alert, but at least let you install it...
